"""HTML report rendering — single-file standalone HTML for GitHub Pages
or curator email distribution.
"""

from __future__ import annotations

import html
from datetime import datetime, timezone

from .detectors import DetectorResult

_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
:root {
  --bg: #0a0e1a; --surface: #111827; --text: #e8ecf4; --text2: #8899b4;
  --accent: #3b82f6; --gold: #f59e0b; --red: #ef4444; --green: #22c55e;
  --border: #2a3550;
}
* { box-sizing: border-box; }
body { font-family: -apple-system, "Inter", sans-serif; background: var(--bg);
       color: var(--text); margin: 0; padding: 32px 24px; line-height: 1.55; }
.wrap { max-width: 960px; margin: 0 auto; }
h1 { font-size: 1.8rem; margin: 0 0 4px; }
.subtitle { color: var(--text2); font-size: 0.95rem; margin-bottom: 28px; }
.detector { background: var(--surface); border: 1px solid var(--border);
            border-radius: 10px; padding: 20px 22px; margin-bottom: 16px; }
.detector h2 { font-size: 1.1rem; margin: 0 0 6px; color: var(--text); }
.headline { display: inline-block; padding: 4px 12px; border-radius: 6px;
            font-weight: 700; font-size: 0.95rem; margin-right: 10px;
            background: rgba(59,130,246,0.18); color: var(--accent); }
.headline.warn { background: rgba(245,158,11,0.18); color: var(--gold); }
.headline.danger { background: rgba(239,68,68,0.18); color: var(--red); }
.unit { color: var(--text2); font-size: 0.85rem; }
.interp { margin-top: 10px; color: var(--text); }
.evidence { margin-top: 12px; padding-top: 12px; border-top: 1px dashed var(--border); }
.evidence summary { cursor: pointer; color: var(--text2); font-size: 0.88rem; }
.evidence-body { margin-top: 10px; font-family: ui-monospace, SFMono-Regular, monospace;
                 font-size: 0.82rem; color: var(--text2); background: rgba(0,0,0,0.2);
                 padding: 10px 14px; border-radius: 6px; white-space: pre-wrap; }
footer { color: var(--text2); font-size: 0.78rem; margin-top: 36px; text-align: center; }
</style>
</head>
<body>
<div class="wrap">
"""

_TAIL = """
<footer>Generated by kamino-vault-counterfactuals · MIT · <a style="color:#3b82f6" href="https://github.com/mkzung/kamino-vault-counterfactuals">github.com/mkzung/kamino-vault-counterfactuals</a></footer>
</div>
</body>
</html>
"""


def _severity(metric: float, unit: str) -> str:
    """Map metric → CSS severity class (default for fractional metrics)."""
    if "fraction" in unit or "utilization" in unit:
        if metric > 0.20:
            return "danger"
        if metric > 0.05:
            return "warn"
    return ""


def as_html(
    results: list[DetectorResult],
    *,
    title: str = "Kamino Vault Counterfactuals Report",
    subtitle: str | None = None,
) -> str:
    """Render results as a standalone HTML document."""
    ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body_parts: list[str] = [_HEAD.replace("{title}", html.escape(title))]
    body_parts.append(f'<h1>{html.escape(title)}</h1>')
    sub = subtitle or f"Generated {ts}"
    body_parts.append(f'<div class="subtitle">{html.escape(sub)}</div>')

    for r in results:
        sev_class = _severity(r.headline_metric, r.headline_unit)
        sev_css = f" {sev_class}" if sev_class else ""
        body_parts.append('<div class="detector">')
        body_parts.append(f'<h2>{html.escape(r.name)}</h2>')
        body_parts.append(
            f'<span class="headline{sev_css}">{r.headline_metric:.4f}</span>'
            f'<span class="unit">{html.escape(r.headline_unit)}</span>'
        )
        body_parts.append(f'<div class="interp">{html.escape(r.interpretation)}</div>')
        body_parts.append('<details class="evidence">')
        body_parts.append('<summary>Evidence</summary>')
        body_parts.append('<div class="evidence-body">')
        body_parts.append(html.escape(_format_evidence(r.evidence)))
        body_parts.append('</div></details></div>')

    body_parts.append(_TAIL)
    return "".join(body_parts)


def _format_evidence(d: dict[str, object]) -> str:
    """Render evidence dict as a pretty-printed string."""
    lines: list[str] = []
    for k, v in d.items():
        if isinstance(v, (int, float)):
            if isinstance(v, float):
                lines.append(f"{k}: {v:.6f}")
            else:
                lines.append(f"{k}: {v:,}")
        elif isinstance(v, dict):
            lines.append(f"{k}:")
            for sk, sv in v.items():
                lines.append(f"  {sk}: {sv}")
        elif isinstance(v, list):
            lines.append(f"{k}: ({len(v)} items)")
            for item in v[:8]:
                lines.append(f"  - {item}")
            if len(v) > 8:
                lines.append(f"  ... ({len(v) - 8} more)")
        else:
            lines.append(f"{k}: {v}")
    return "\n".join(lines)
